In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
pd.set_option('display.max_columns', None)
import os
from modules.TravelSurveyAnalysis import TravelSurveyAnalysis

if 'TravelSurvey' in os.getcwd():
    data_folder = '../../data/'
elif 'data_analysis' in os.getcwd():
    data_folder = '../data/'
else:
    data_folder = './data/'

source_folder_path = data_folder + 'netherlands/'
destination_folder_path = data_folder + 'netherlands/'

In [2]:
extended_mode_index_map_ovin = {
                    1: 'Train',
                    2: 'Coach/bus (private bus transport only)',
                    3: 'Subway', 
                    4: 'Tram',
                    5: 'Bus (public transport only)', 
                    6: 'Driver car',
                    7: 'Delivery van',
                    8: 'Truck',
                    9: 'Camper',
                    10: 'Passenger car', 
                    11: 'Cab',
                    12: 'Engine',
                    13: 'Moped',
                    14: 'Moped',
                    15: 'Bicycle (electric and/or non-electric)', 
                    16: 'Ride a bicycle as a passenger',
                    17: 'Agricultural vehicle',
                    18: 'Boat (scheduled service, ferry service)',
                    19: 'Aeroplane',
                    20: 'Skates/inline skates/step',
                    21: 'Disabled transport vehicle',
                    22: 'On foot',
                    23: 'Pram',
                    24: 'Otherwise',
}

# from 2017 onwards
extended_mode_index_map_odin = {
                    1: 'Passenger car',
                    2: 'Train',
                    3: 'Bus', 
                    4: 'Tram',
                    5: 'Subway', 
                    6: 'Speed pedelec',
                    7: 'Electric bike',
                    8: 'Non-electric bicycle',
                    9: 'On foot',
                    10: 'Coach', 
                    11: 'Delivery van',
                    12: 'Truck',
                    13: 'Camper',
                    14: 'Taxi/Taxi van',
                    15: 'Agricultural vehicle', 
                    16: 'Engine',
                    17: 'Moped',
                    18: 'Moped',
                    19: 'Disabled transport vehicle with motor',
                    20: 'Disabled transport vehicle without engine',
                    21: 'Skates/inline skates/step',
                    22: 'Boat',
                    23: 'Different with engine',
                    24: 'Otherwise without engine',
}

In [3]:
expansion_factor_trip = 'FactorV'
expansion_factor_person = 'FactorP'
expansion_factor_family = 'FactorH'
origin_column = 'VertGem'
destination_column = 'AankGem'
residence_column = 'WoGem'

dict_year_data_correspondence = {
    '2010': 'OViN2010_Databestand.csv',
    '2013': 'OViN2013_Databestand.csv',
    '2017': 'OViN2017_Databestand.csv',
    '2018': 'ODiN2018_Databestand_v2.0.csv',
    '2019': 'ODiN2019_Databestand_v2.0.csv',
}

code_column = 'CBS code'

dict_columns_ovin = {
    'Mode Share': {'column': 'Hvm',
                   'index_map': extended_mode_index_map_ovin},
    'Gender': {'column': 'Geslacht',
                   'index_map': {1: 'Man', 2: 'Woman'}},
    'Age': {'column': 'Leeftijd',
                   'index_map': {}}
}

dict_columns_odin = {
    'Mode Share': {'column': 'Hvm',
                   'index_map': extended_mode_index_map_odin},
    'Gender': {'column': 'Geslacht',
                   'index_map': {1: 'Man', 2: 'Woman'}},
    'Age': {'column': 'Leeftijd',
                   'index_map': {}}
}

dict_expansion_factor = {
      'No expansion factor': False,
      'Person expansion factor': expansion_factor_person,
      'Trip expansion factor': expansion_factor_trip,
      'Family expansion factor': expansion_factor_family
}

In [4]:
tsa = TravelSurveyAnalysis(source_folder_path, destination_folder_path,
                           expansion_factor_trip, expansion_factor_person,
                           origin_column, destination_column, residence_column)

df_codes = tsa.read_data('list_code_municipalities_netherlands.csv')
df_codes = df_codes.set_index('Municipality')

In [5]:
year = '2018'

In [6]:
filename = dict_year_data_correspondence[year]
data = tsa.read_data(filename)

In [7]:
if int(year) <= 2017:
    data = data.rename(columns = {'Wogem': 'WoGem'})
    dict_columns = dict_columns_ovin
else:
    dict_columns = dict_columns_odin

In [8]:
variable = 'Gender'

In [9]:
variable = 'Mode Share'

In [10]:
city = 'Amsterdam'
city_code = df_codes.loc[city][code_column]
column = dict_columns[variable]['column']
index_map = dict_columns[variable]['index_map']

In [11]:
tsa.calculate_distribution_city(data, city, city_code, column, index_map,
                                expansion_factor = expansion_factor_trip,
                                year = year)

                                             FactorV
Hvm_new
Boat                                        0.163240
Bus                                         4.042121
Coach                                       0.048908
Delivery van                                0.624239
Different with engine                       0.092686
Disabled transport vehicle with motor       0.218515
Electric bike                               1.300991
Engine                                      0.283274
Moped                                       1.272502
Non-electric bicycle                       35.575341
On foot                                    23.660750
Otherwise without engine                    0.027214
Passenger car                              12.776604
Skates/inline skates/step                   0.014044
Subway                                      9.480319
Taxi/Taxi van                               0.131707
Train                                       0.762261
Tram                                        9.457409
Truck                                       0.067877
Speed pedelec                               0.000000
Camper                                      0.000000
Agricultural vehicle                        0.000000
Disabled transport vehicle without engine   0.000000

In [12]:
city = 'All'
city_code = df_codes.loc[city][code_column]
column = dict_columns[variable]['column']
index_map = dict_columns[variable]['index_map']

In [13]:
print(city)
print(city_code)
print(column)
print(index_map)
print(expansion_factor_trip)

All
0
Hvm
{1: 'Passenger car', 2: 'Train', 3: 'Bus', 4: 'Tram', 5: 'Subway', 6: 'Speed pedelec', 7: 'Electric bike', 8: 'Non-electric bicycle', 9: 'On foot', 10: 'Coach', 11: 'Delivery van', 12: 'Truck', 13: 'Camper', 14: 'Taxi/Taxi van', 15: 'Agricultural vehicle', 16: 'Engine', 17: 'Moped', 18: 'Moped', 19: 'Disabled transport vehicle with motor', 20: 'Disabled transport vehicle without engine', 21: 'Skates/inline skates/step', 22: 'Boat', 23: 'Different with engine', 24: 'Otherwise without engine'}
FactorV

In [14]:
tsa.calculate_distribution_city(data, city, city_code, column, index_map,
                                expansion_factor = expansion_factor_trip,
                                year = year)

                                             FactorV
Hvm_new
Agricultural vehicle                        0.028504
Boat                                        0.030619
Bus                                         2.820066
Camper                                      0.031247
Coach                                       0.103540
Delivery van                                1.688305
Different with engine                       0.059494
Disabled transport vehicle with motor       0.234515
Disabled transport vehicle without engine   0.021697
Electric bike                               3.631218
Engine                                      0.207096
Moped                                       0.892300
Non-electric bicycle                       22.483615
On foot                                    14.697099
Otherwise without engine                    0.039846
Passenger car                              42.656885
Skates/inline skates/step                   0.100139
Speed pedelec                               0.007332
Subway                                      1.373806
Taxi/Taxi van                               0.241337
Train                                       7.353789
Tram                                        1.053905
Truck                                       0.243645