In [7]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None  # default='warn'
import os
from modules.TravelSurveyAnalysis import TravelSurveyAnalysis

if 'TravelSurvey' in os.getcwd():
    data_folder = '../../data/'
elif 'data_analysis' in os.getcwd():
    data_folder = '../data/'
else:
    data_folder = './data/'

source_folder_path = data_folder + 'OD/OD_2007/'
destination_folder_path = data_folder + 'OD/OD_2007/'

In [8]:
expansion_factor_trip = 'FE_VIA'
expansion_factor_person = 'FE_PESS'

tsa = TravelSurveyAnalysis(source_folder_path, destination_folder_path,
                           expansion_factor_trip, expansion_factor_person)

In [ ]:
original_filename = 'OD_2007_v2d.csv'

In [9]:
'''
Run in the first time for file treatment. If the file '{original_filename}_treated.csv'
already exists on the source folder path, it's not necessary
'''
# tsa.treat_csv_file_generated_from_dbf_and_save(original_filename)

"\nRun in the first time for file treatment. If the file 'OD_2007_v2d_treated.csv'\nalready exists on the source folder path, it's not necessary\n"

In [10]:
filename = original_filename[:-4] + '_treated.csv'

data = tsa.read_data(filename)

In [11]:
data

,ZONA,MUNI_DOM,CO_DOM_X,CO_DOM_Y,ID_DOM,F_DOM,FE_DOM,DOM,CD_ENTRE,DATA,TIPO_DOM,NO_MORAD,TOT_FAM,ID_FAM,F_FAM,FE_FAM,FAMILIA,NO_MORAF,CONDMORA,QT_RADIO,QT_GEL1,QT_GEL2,QT_TVCOR,QT_FREEZ,QT_VIDEO,QT_BANHO,QT_MOTO,QT_AUTO,QT_ASPIR,QT_MLAVA,QT_EMPRE,QT_MICRO,QT_BICICLE,NAO_DCL_IT,CRITERIOBR,ANO_AUTO1,ANO_AUTO2,ANO_AUTO3,RENDA_FA,CD_RENFA,ID_PESS,F_PESS,FE_PESS,PESSOA,SIT_FAM,IDADE,SEXO,ESTUDA,GRAU_INS,CD_ATIVI,CO_REN_I,VL_REN_I,ZONA_ESC,MUNIESC,CO_ESC_X,CO_ESC_Y,TIPO_ESC,ZONATRA1,MUNITRA1,CO_TR1_X,CO_TR1_Y,TRAB1_RE,TRABEXT1,OCUP1,SETOR1,VINC1,ZONATRA2,MUNITRA2,CO_TR2_X,CO_TR2_Y,TRAB2_RE,TRABEXT2,OCUP2,SETOR2,VINC2,N_VIAG,FE_VIA,DIA_SEM,TOT_VIAG,ZONA_O,MUNI_O,CO_O_X,CO_O_Y,ZONA_D,MUNI_D,CO_D_X,CO_D_Y,ZONA_T1,MUNI_T1,CO_T1_X,CO_T1_Y,ZONA_T2,MUNI_T2,CO_T2_X,CO_T2_Y,ZONA_T3,MUNI_T3,CO_T3_X,CO_T3_Y,MOTIVO_O,MOTIVO_D,MOT_SRES,SERVIR_O,SERVIR_D,MODO1,MODO2,MODO3,MODO4,H_SAIDA,MIN_SAIDA,ANDA_O,H_CHEG,MIN_CHEG,ANDA_D,DURACAO,MODOPRIN,TIPVG,PAG_VIAG,TP_ESAUTO,VL_EST,PE_BICI,TP_ESBICI,DISTANCIA,ID_ORDEM
0,1,36,333729.0,7394430.0,10001,1,17.97777,1,6,08/17/2007,1,1,1,1000101,1,17.97777,1,1,1,1,1,0,1,0,1,1,0,1,0,0,0,0,0,1,5,1998,0,0,850.0,1,100010101,1,21.80211,1,1,29,1,1,4,1,1,850,0,0,0.00,0.00,0,3,36,333221.17,7394102.88,2,2,906,12,1,0,0,0.0,0.0,0,0,0,0,0,1,25.33996,6,2,1,36,333729.00,7394430.00,3,36,333221.17,7394102.88,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,8,3,3,2,2,16,0,0,0,8,0,0,8,10,0,10,16,3,0,0,0,1,0,604.07,1
1,1,36,333729.0,7394430.0,10001,0,17.97777,1,6,08/17/2007,1,1,1,1000101,0,17.97777,1,1,1,1,1,0,1,0,1,1,0,1,0,0,0,0,0,1,5,1998,0,0,850.0,1,100010101,0,21.80211,1,1,29,1,1,4,1,1,850,0,0,0.00,0.00,0,3,36,333221.17,7394102.88,2,2,906,12,1,0,0,0.0,0.0,0,0,0,0,0,2,25.33996,6,2,3,36,333221.17,7394102.88,1,36,333729.00,7394430.00,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,3,8,3,2,2,16,0,0,0,17,30,0,17,40,0,10,16,3,0,0,0,1,0,604.07,2
2,1,36,333858.0,7394484.0,10018,1,17.67677,18,6,08/16/2007,1,2,1,1001801,1,17.67677,1,2,1,6,0,0,1,1,1,1,0,1,0,1,0,0,1,1,4,1989,0,0,2600.0,1,100180101,1,21.43708,1,1,51,1,1,4,1,1,2000,0,0,0.00,0.00,0,327,13,323571.90,7418657.69,2,2,803,10,1,0,0,0.0,0.0,0,0,0,0,0,1,20.10459,5,2,1,36,333858.00,7394484.00,327,13,323571.90,7418657.69,91,36,330062.21,7397396.57,0,0,0.0,0.0,0,0,0.0,0.0,8,3,3,2,2,12,13,0,0,4,30,2,5,45,2,75,12,1,2,0,0,0,0,26271.11,3
3,1,36,333858.0,7394484.0,10018,0,17.67677,18,6,08/16/2007,1,2,1,1001801,0,17.67677,1,2,1,6,0,0,1,1,1,1,0,1,0,1,0,0,1,1,4,1989,0,0,2600.0,1,100180101,0,21.43708,1,1,51,1,1,4,1,1,2000,0,0,0.00,0.00,0,327,13,323571.90,7418657.69,2,2,803,10,1,0,0,0.0,0.0,0,0,0,0,0,2,20.10459,5,2,327,13,323571.90,7418657.69,1,36,333858.00,7394484.00,6,36,333245.88,7396047.21,0,0,0.0,0.0,0,0,0.0,0.0,3,8,3,2,2,13,12,0,0,18,10,2,19,30,2,80,12,1,2,0,0,0,0,26271.11,4
4,1,36,333858.0,7394484.0,10018,0,17.67677,18,6,08/16/2007,1,2,1,1001801,0,17.67677,1,2,1,6,0,0,1,1,1,1,0,1,0,1,0,0,1,1,4,1989,0,0,2600.0,1,100180102,1,21.43708,2,2,52,2,1,1,7,1,600,0,0,0.00,0.00,0,0,0,0.00,0.00,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0.00000,0,0,0,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196693,460,25,297897.0,7409051.0,4601115,0,75.79343,1115,6,04/12/2008,1,6,1,460111501,0,75.79343,1,6,2,1,1,0,1,0,1,2,2,1,0,1,0,0,0,1,5,1999,0,0,4070.0,1,46011150104,0,82.64561,4,3,20,1,1,4,1,1,685,0,0,0.00,0.00,0,424,2,307491.23,7400087.06,2,2,925,3,1,0,0,0.0,0.0,0,0,0,0,0,2,96.05660,6,2,424,2,307491.23,7400087.06,460,25,297897.00,7409051.00,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,1,8,1,2,2,14,0,0,0,17,0,1,18,0,1,60,14,2,0,0,0,0,0,13130.17,196694
196694,460,25,297897.0,7409051.0,4601115,0,75.79343,1115,6,04/12/2008,1,6,1,460111501,0,75.79343,1,6,2,1,1,0,1,0,1,2,2,1,0,1,0,0,0,1,5,1999,0,0,4070.0,1,46011150105,1,82.64561,5,3,11,2,3,2,8,2,0,460,25,297434.44,7409203.51,1,0,0,0.00,0.00,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,1,96.05660,6,2,460,25,297897.00,7409051.00,460,25,297434.44,7409203.51,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,8,4,4,2,2,16,0,0,0,12,0,0,12,15,0,15,16,3,0,0,0,1,0,487.05,196695
196695,460,25,297897.0,7409051.0,4601115,0,75.79343,1115,6,04/12/2008,1,6,1,460111501,0,75.79343,1,6,2,1,1,0,1,0,1,2,2,1,0,1,0,0,0,1,5,1999,0,0,4070.0,1,46011150105,0,82.64561,5,3,11,2,3,2,8,2,0,460,25,297434.44,7409203.51,1,0,0,0.00,0.00,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2,96.05660,6,2,460,25,297434.44,7409203.51,460,25,297897.00,7409051.00,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,4,8,4,2,2,16,0,0,0,17,40,0,18,0,0,20,16,3,0,0,0,1,0,487.05,196696
196696,460,25,297897.0,7409051.0,4601115,0,75.79343,1115,6,04/12/2008,1,6,1,460111501,0,75.79343,1,6,2,1,1,0,1,0,1,2,2,1,0,1,0,0,0,1,5,1999,0,0,4070.0,1,46011150106,1,82.64561,6,3,4,1,2,1,6,2,0,460,25,304626.52,7415445.73,1,0,0,0.00,0.00,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,1,96.05660,6,2,460,25,297897.00,7409051.00,460,25,304626.52,7415445.73,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,8,4,4,2,2,16,0,0,0,7,45,0,7,55,0,10,16,3,0,0,0,1,0,9283.27,196697
196697,460,25,297897.0,7409051.0,4601115,0,75.79343,1115,6,04/12/2008,1,6,1,460111501,0,75.79343,1,6,2,1,1,0,1,0,1,2,2,1,0,1,0,0,0,1,5,1999,0,0,4070.0,1,46011150106,0,82.64561,6,3,4,1,2,1,6,2,0,460,25,304626.52,7415445.73,1,0,0,0.00,0.00,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,2,96.05660,6,2,460,25,304626.52,7415445.73,460,25,297897.00,7409051.00,0,0,0.00,0.00,0,0,0.0,0.0,0,0,0.0,0.0,4,8,4,2,2,16,0,0,0,12,0,0,12,10,0,10,16,3,0,0,0,1,0,9283.27,196698

In [12]:
data['FE_VIA'].sum()

38094384.52149001

In [13]:
data_sp = data[(data['MUNI_O'] == 36) | (data['MUNI_D'] == 36)]

In [14]:
data_sp['FE_VIA'].sum()

25431954.064270005

## Mode share

Columns correspondence:

1 - Coletivo

2 - Individual

3 - A pé

4 - Bicicleta

In [15]:
mode_column = 'TIPVG'
mode_index_map = {1: 'Coletivo', 2: 'Individual', 3: 'A pé', 4: 'Bicicleta'}
df = tsa.calculate_distribution(data, mode_column, expansion_factor_trip, mode_index_map)
df

               FE_VIA
TIPVG_new
A pé        33.136240
Bicicleta    0.797566
Coletivo    36.522029
Individual  29.544165

In [16]:
tsa.calculate_distribution(data_sp, mode_column, expansion_factor_trip, mode_index_map)

               FE_VIA
TIPVG_new
A pé        28.949999
Bicicleta    0.612568
Coletivo    39.770204
Individual  30.667229